DO $$ BEGIN
 CREATE TYPE "public"."billing_interval" AS ENUM('monthly', 'yearly');
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 CREATE TYPE "public"."credit_transaction_type" AS ENUM('subscription_credit', 'ai_resume_generation', 'refund', 'manual_adjustment', 'credit_expiry');
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 CREATE TYPE "public"."plan_type" AS ENUM('free', 'growth', 'professional');
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 CREATE TYPE "public"."resume_status" AS ENUM('draft', 'published', 'archived');
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 CREATE TYPE "public"."status" AS ENUM('active', 'canceled', 'incomplete', 'incomplete_expired', 'past_due', 'trialing', 'unpaid');
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 CREATE TYPE "public"."subscription_status" AS ENUM('active', 'canceled', 'expired', 'past_due');
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "resume-builder_account" (
	"user_id" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"provider_account_id" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "resume-builder_account_provider_provider_account_id_pk" PRIMARY KEY("provider","provider_account_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "resume-builder_credit_log" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"user_id" varchar(255) NOT NULL,
	"amount" integer NOT NULL,
	"type" "credit_transaction_type" NOT NULL,
	"description" varchar(255),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "resume-builder_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "resume-builder_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"created_by" varchar(255) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "resume-builder_resume" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"user_id" varchar(255) NOT NULL,
	"name" varchar(255) DEFAULT 'Untitled Resume',
	"is_public" boolean DEFAULT false,
	"data" jsonb DEFAULT '{"personalInfo":{"title":"Personal Info"},"workExperience":{"title":"Work Experience","items":[]},"education":{"title":"Education","items":[]},"skills":{"title":"Skills","items":[]},"projects":{"title":"Projects","items":[]},"achievements":{"title":"Achievements","items":[]},"awards":{"title":"Awards","items":[]},"graphs":{"title":"Graphs","items":[]},"goals":{"title":"Goals","items":[]},"references":{"title":"References","items":[]},"publications":{"title":"Publications","items":[]},"voluntaryWork":{"title":"Voluntary Work","items":[]},"certifications":{"title":"Certifications","items":[]},"languages":{"title":"Languages","items":[]},"socialMedia":{"title":"Social Media","items":[]}}'::jsonb,
	"status" "resume_status" DEFAULT 'draft',
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"order" jsonb DEFAULT '[{"id":"personalInfo","title":"Personal Info"},{"id":"workExperience","title":"Work Experience"},{"id":"education","title":"Education"},{"id":"skills","title":"Skills"},{"id":"projects","title":"Projects"}]'::jsonb,
	"settings" jsonb DEFAULT '{}'::jsonb
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "resume-builder_session" (
	"session_token" varchar(255) PRIMARY KEY NOT NULL,
	"user_id" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "resume-builder_subscription" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"user_id" varchar(255) NOT NULL,
	"stripe_customer_id" varchar(255),
	"stripe_price_id" varchar(255) NOT NULL,
	"stripe_subscription_id" varchar(255) NOT NULL,
	"status" "subscription_status" NOT NULL,
	"plan" "plan_type" NOT NULL,
	"interval" "billing_interval" NOT NULL,
	"start_date" timestamp with time zone DEFAULT now() NOT NULL,
	"end_date" timestamp with time zone,
	"canceled_at" timestamp with time zone,
	"last_credit_refresh" timestamp with time zone DEFAULT now() NOT NULL,
	"next_credit_refresh" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "resume-builder_subscription_stripe_subscription_id_unique" UNIQUE("stripe_subscription_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "resume-builder_template" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"color_options" jsonb DEFAULT '[]'::jsonb,
	"headline_capitalization" boolean DEFAULT false,
	"font_options" jsonb DEFAULT '[]'::jsonb,
	"background" jsonb DEFAULT '{"className":"bg-white","opacity":1}'::jsonb
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "resume-builder_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"email_verified" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"image" varchar(255),
	"onboarding_done" boolean DEFAULT false,
	"stripe_customer_id" varchar(255) DEFAULT '',
	"first_name" varchar(255) DEFAULT '',
	"last_name" varchar(255) DEFAULT '',
	"phone_number" varchar(20) DEFAULT '',
	"location" varchar(255) DEFAULT '',
	"date_of_birth" timestamp with time zone,
	"nationality" varchar(255) DEFAULT '',
	"address" varchar(255) DEFAULT '',
	"city" varchar(255) DEFAULT '',
	"postal_code" varchar(255) DEFAULT '',
	"country" varchar(255) DEFAULT '',
	"website" varchar(200) DEFAULT '',
	"bio" text DEFAULT '',
	"credits" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "resume-builder_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "resume-builder_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "resume-builder_account" ADD CONSTRAINT "resume-builder_account_user_id_resume-builder_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."resume-builder_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "resume-builder_credit_log" ADD CONSTRAINT "resume-builder_credit_log_user_id_resume-builder_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."resume-builder_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "resume-builder_post" ADD CONSTRAINT "resume-builder_post_created_by_resume-builder_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."resume-builder_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "resume-builder_resume" ADD CONSTRAINT "resume-builder_resume_user_id_resume-builder_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."resume-builder_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "resume-builder_session" ADD CONSTRAINT "resume-builder_session_user_id_resume-builder_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."resume-builder_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "resume-builder_subscription" ADD CONSTRAINT "resume-builder_subscription_user_id_resume-builder_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."resume-builder_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "account_user_id_idx" ON "resume-builder_account" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "credit_log_user_id_idx" ON "resume-builder_credit_log" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "created_by_idx" ON "resume-builder_post" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "name_idx" ON "resume-builder_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "session_user_id_idx" ON "resume-builder_session" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "subscription_user_id_idx" ON "resume-builder_subscription" USING btree ("user_id");