import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { Toaster } from "sonner";
import { type Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { ReactQueryProvider } from "@/components/providers/ReactQueryProvider";
import { SubscribeToPremiumDialogProvider } from "@/components/providers/SubscribeToPremiumDialog";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body suppressHydrationWarning>
        <SessionProvider>
          <ReactQueryProvider>
            <Toaster richColors />
            <SubscribeToPremiumDialogProvider>
              {children}
            </SubscribeToPremiumDialogProvider>
          </ReactQueryProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
