import "@/styles/globals.css";
import LocalFont from "next/font/local";
import Footer from "@/components/footer";

const PSMedian = LocalFont({
  src: "../fonts/ps-median.woff2",
  variable: "--font-ps-median",
});

const PSSlim = LocalFont({
  src: "../fonts/ps-slim.woff2",
  variable: "--font-ps-slim",
});

const Tobe = LocalFont({
  src: "../fonts/tobe.otf",
  variable: "--font-tobe",
});

import { DialogProvider } from "@/components/providers/DialogProvider";
import { GeistSans } from "geist/font/sans";
import { Toaster } from "sonner";
import { type Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { ReactQueryProvider } from "@/components/providers/ReactQueryProvider";
import { SubscribeToPremiumDialogProvider } from "@/components/providers/SubscribeToPremiumDialog";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${PSMedian.variable} ${PSSlim.variable} ${Tobe.variable} ${GeistSans.variable}`}
    >
      <body suppressHydrationWarning>
        <SessionProvider>
          <ReactQueryProvider>
            <Toaster richColors />
            <SubscribeToPremiumDialogProvider>
              <DialogProvider>{children}</DialogProvider>
            </SubscribeToPremiumDialogProvider>
          </ReactQueryProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
